name: 'Release'
description: 'Creates github releases'
author: 'Nick Cipollo'
inputs:
  artifact:
    description: 'A path to an optional artifact to upload to the release.'
    default: ''
  artifactContentType:
    description: 'The content type of the artifact. Defaults to raw'
    default: ''
  body:
    description: 'An optional body for the release.'
    default: ''
  bodyFile:
    description: 'An optional body file for the release. This should be the path to the file'
    default: ''  
  commit:
    description: 'An optional commit reference. This will be used to create the tag if it doesn't exist.'
    default: ''
  name:
    description: 'An optional name for the release. If this is omitted the tag will be used.'
    default: ''
  tag:
    description: 'An optional tag for the release. If this is omitted the git ref will be used (if it's a tag).'
    default: ''
  token:
    description: 'The Github token.'
    required: true
    default: ''
runs:
  using: 'node12'
  main: 'lib/main.js'
